import type { EnumMemberKey, EnumName, EnumValue } from '@vben/types';

export type EnumTone =
  | 'category'
  | 'danger'
  | 'neutral'
  | 'paused'
  | 'queued'
  | 'running'
  | 'success'
  | 'warning';

export interface EnumPresentation {
  readonly categoryHue?: number;
  readonly emphasis?: 'solid' | 'subtle';
  readonly icon?: string;
  readonly tone: EnumTone;
}

type SemanticEnumTone = Exclude<EnumTone, 'category'>;

const SEMANTIC_TONE_PRESETS = {
  danger: {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  neutral: { icon: 'lucide:circle-minus', tone: 'neutral' },
  paused: { icon: 'lucide:circle-pause', tone: 'paused' },
  queued: { icon: 'lucide:clock-3', tone: 'queued' },
  running: { icon: 'lucide:loader-circle', tone: 'running' },
  success: { icon: 'lucide:circle-check', tone: 'success' },
  warning: {
    emphasis: 'solid',
    icon: 'lucide:triangle-alert',
    tone: 'warning',
  },
} as const satisfies Record<SemanticEnumTone, EnumPresentation>;

/**
 * Explicit semantic classification for lifecycle/result enums. Entries not in
 * this map are taxonomies and retain their stable categorical hue below.
 */
const SEMANTIC_ENUM_TONES = {
  'AdmissionOutcome.allow': 'success',
  'AdmissionOutcome.deny': 'danger',
  'AdmissionOutcome.defer': 'warning',
  'ApprovalStatus.not_required': 'neutral',
  'ApprovalStatus.pending': 'queued',
  'ApprovalStatus.approved': 'success',
  'ApprovalStatus.rejected': 'danger',
  'ApprovalStatus.expired': 'neutral',
  'CapitalAllocationState.allocated': 'success',
  'CapitalAllocationState.locked': 'running',
  'CapitalAllocationState.spent': 'success',
  'CapitalAllocationState.released': 'neutral',
  'CapitalAllocationState.impaired': 'danger',
  'CapabilityReason.control_plane_not_ready': 'danger',
  'CapabilityReason.catalog_baseline_missing': 'danger',
  'CapabilityReason.operational_phase_blocks_reports': 'warning',
  'CapabilityReason.runtime_mode_report_only': 'neutral',
  'CapabilityReason.kill_switch_blocks_entries': 'danger',
  'CapabilityReason.operational_phase_blocks_submission': 'warning',
  'CapabilityReason.no_serving_evidence': 'danger',
  'CatalogFilterReason.inactive': 'neutral',
  'CatalogFilterReason.closed': 'neutral',
  'CatalogFilterReason.clob_disabled': 'warning',
  'CatalogFilterReason.orders_not_accepted': 'warning',
  'CatalogSyncStatus.committed': 'success',
  'CatalogSyncStatus.failed': 'danger',
  'DataQualityStatus.fresh': 'success',
  'DataQualityStatus.acceptable': 'success',
  'DataQualityStatus.degraded': 'warning',
  'DataQualityStatus.stale': 'warning',
  'DataQualityStatus.insufficient': 'warning',
  'DomainSourceExpectationStatus.not_started': 'queued',
  'DomainSourceExpectationStatus.live': 'success',
  'DomainSourceExpectationStatus.stale': 'warning',
  'DomainSourceExpectationStatus.credential_blocked': 'danger',
  'DomainSourceExpectationStatus.error': 'danger',
  'DomainSourceExpectationStatus.unsupported': 'neutral',
  'EntryConditionState.not_required': 'neutral',
  'EntryConditionState.waiting': 'queued',
  'EntryConditionState.unavailable': 'danger',
  'EntryConditionState.confirming': 'running',
  'EntryConditionState.qualified': 'success',
  'EntryConditionState.consumed': 'success',
  'EntryConditionState.expired': 'neutral',
  'EntryConditionState.invalidated': 'danger',
  'EventStatus.active': 'success',
  'EventStatus.closed': 'neutral',
  'EventStatus.archived': 'neutral',
  'EventStatus.unknown': 'warning',
  'ExecutionOrderState.planned': 'queued',
  'ExecutionOrderState.accepted': 'running',
  'ExecutionOrderState.submitted': 'running',
  'ExecutionOrderState.partially_filled': 'running',
  'ExecutionOrderState.filled': 'success',
  'ExecutionOrderState.cancel_requested': 'running',
  'ExecutionOrderState.cancelled': 'neutral',
  'ExecutionOrderState.failed': 'danger',
  'ExecutionOrderState.ambiguous': 'danger',
  'ExitState.not_started': 'queued',
  'ExitState.monitoring': 'running',
  'ExitState.triggered': 'running',
  'ExitState.order_submitted': 'running',
  'ExitState.partially_exited': 'running',
  'ExitState.exited': 'success',
  'ExitState.failed': 'danger',
  'ExitState.manual_required': 'warning',
  'FactorValueState.scored': 'success',
  'FactorValueState.missing_input': 'danger',
  'FactorValueState.not_applicable': 'neutral',
  'FactorValueState.indeterminate': 'warning',
  'FeatureCellState.observed': 'success',
  'FeatureCellState.substituted': 'warning',
  'FeatureCellState.missing': 'danger',
  'FeatureCellState.not_applicable': 'neutral',
  'FeatureParityLatchState.open': 'danger',
  'FeatureParityLatchState.clear': 'success',
  'FeedbackCycleStatus.queued': 'queued',
  'FeedbackCycleStatus.running': 'running',
  'FeedbackCycleStatus.succeeded': 'success',
  'FeedbackCycleStatus.failed': 'danger',
  'FeedbackCycleStatus.cancelled': 'neutral',
  'FeedbackCycleStatus.quarantined': 'warning',
  'FeedbackRecipeTemplateStatus.draft': 'queued',
  'FeedbackRecipeTemplateStatus.approved': 'success',
  'FeedbackRecipeTemplateStatus.retired': 'neutral',
  'KillSwitchState.closed': 'success',
  'KillSwitchState.execution_halted': 'danger',
  'KillSwitchState.exit_only': 'warning',
  'KillSwitchState.emergency_halted': 'danger',
  'LinkageStatus.resolved': 'success',
  'LinkageStatus.unresolved': 'warning',
  'LinkageStatus.overridden': 'warning',
  'MarketStatus.discovered': 'queued',
  'MarketStatus.active': 'success',
  'MarketStatus.filtered': 'neutral',
  'MarketStatus.paused': 'paused',
  'MarketStatus.manually_blocked': 'danger',
  'MarketStatus.settled': 'success',
  'MarketStatus.delisted': 'neutral',
  'ModeDenialReason.report_only': 'danger',
  'ModeDenialReason.recommendation_ineligible': 'danger',
  'ModeDenialReason.risk_envelope_invalid': 'danger',
  'ModeDenialReason.kill_switch_blocks_entry': 'danger',
  'ModeDenialReason.auto_execution_not_allowed': 'danger',
  'OrderIntentStatus.draft': 'queued',
  'OrderIntentStatus.pending_approval': 'queued',
  'OrderIntentStatus.approved': 'success',
  'OrderIntentStatus.approved_by_policy': 'success',
  'OrderIntentStatus.admission_pending': 'running',
  'OrderIntentStatus.admission_rejected': 'danger',
  'OrderIntentStatus.submitted': 'running',
  'OrderIntentStatus.partially_filled': 'running',
  'OrderIntentStatus.filled': 'success',
  'OrderIntentStatus.rejected': 'danger',
  'OrderIntentStatus.cancelled': 'neutral',
  'OrderIntentStatus.failed': 'danger',
  'OrderIntentStatus.expired': 'neutral',
  'OrderIntentStatus.invalidated': 'danger',
  'OutcomeReconciliationTaskStatus.pending': 'queued',
  'OutcomeReconciliationTaskStatus.delivering': 'running',
  'OutcomeReconciliationTaskStatus.retrying': 'running',
  'OutcomeReconciliationTaskStatus.completed': 'success',
  'PolicyRevisionStatus.draft': 'queued',
  'PolicyRevisionStatus.validated': 'success',
  'PolicyValidationCode.schema_version_mismatch': 'danger',
  'PolicyValidationCode.resource_kind_mismatch': 'danger',
  'PolicyValidationCode.semantic_constraint': 'danger',
  'PolicyValidationCode.dependency_unavailable': 'danger',
  'PolicyValidationCode.artifact_incompatible': 'danger',
  'PolicyValidationCode.credential_unavailable': 'danger',
  'PolicyValidationCode.schedule_invalid': 'danger',
  'PolicyValidationCode.authorization_denied': 'danger',
  'PositionLedgerState.open': 'running',
  'PositionLedgerState.closing': 'running',
  'PositionLedgerState.closed': 'success',
  'PositionLedgerState.settled': 'success',
  'RecommendationReportStatus.prepared': 'queued',
  'RecommendationReportStatus.published': 'success',
  'RecommendationReportStatus.superseded': 'neutral',
  'RecommendationReportStatus.obsolete': 'neutral',
  'RecommendationReportStatus.revoked': 'danger',
  'RecommendationReportStatus.expired': 'neutral',
  'RecommendationStatus.prepared': 'queued',
  'RecommendationStatus.published': 'success',
  'RecommendationStatus.superseded': 'neutral',
  'RecommendationStatus.obsolete': 'neutral',
  'RecommendationStatus.revoked': 'danger',
  'RecommendationStatus.expired': 'neutral',
  'RecommendationStatus.intent_created': 'running',
  'RecommendationStatus.executed': 'success',
  'ReportFactDeliveryStatus.pending': 'queued',
  'ReportFactDeliveryStatus.delivering': 'running',
  'ReportFactDeliveryStatus.retrying': 'running',
  'ReportFactDeliveryStatus.failed': 'danger',
  'ReportFactDeliveryStatus.verified': 'success',
  'ReportFactDeliveryStatus.cancelled': 'neutral',
  'ReportRunStatus.queued': 'queued',
  'ReportRunStatus.running': 'running',
  'ReportRunStatus.succeeded': 'success',
  'ReportRunStatus.failed': 'danger',
  'ReportRunStatus.skipped': 'neutral',
  'ReportRunStatus.abandoned': 'neutral',
  'ResolutionProjectionStatus.pending': 'queued',
  'ResolutionProjectionStatus.delivering': 'running',
  'ResolutionProjectionStatus.retry_scheduled': 'warning',
  'ResolutionProjectionStatus.mapping_blocked': 'warning',
  'ResolutionProjectionStatus.quarantined': 'warning',
  'ResolutionProjectionStatus.excluded': 'neutral',
  'ResolutionProjectionStatus.verified': 'success',
  'ResolutionProjectionErrorCode.catalog_mapping_unavailable': 'danger',
  'ResolutionProjectionErrorCode.invalid_observation': 'danger',
  'ResolutionProjectionErrorCode.persistence_unavailable': 'danger',
  'ResolutionProjectionErrorCode.external_dependency_unavailable': 'danger',
  'ResolutionProjectionErrorCode.unexpected_transient': 'danger',
  'RuntimeActivityStatus.pending': 'queued',
  'RuntimeActivityStatus.running': 'running',
  'RuntimeActivityStatus.succeeded': 'success',
  'RuntimeActivityStatus.failed': 'danger',
  'RuntimeActivityStatus.cancelled': 'neutral',
  'RuntimeActivityStatus.attention': 'warning',
  'RuntimeActivityStatus.skipped': 'neutral',
  'SettlementAuthorizationState.not_required': 'neutral',
  'SettlementAuthorizationState.pending': 'queued',
  'SettlementAuthorizationState.approved': 'success',
  'SettlementAuthorizationState.revoked': 'danger',
  'SettlementAuthorizationState.consumed': 'success',
  'SettlementAuthorizationState.expired': 'neutral',
  'SettlementCaseState.discovered': 'queued',
  'SettlementCaseState.prepared': 'queued',
  'SettlementCaseState.submitted': 'running',
  'SettlementCaseState.confirmed': 'success',
  'SettlementCaseState.retry_scheduled': 'warning',
  'SettlementCaseState.reconciliation_required': 'warning',
  'SettlementCaseState.manual_required': 'warning',
  'SettlementCaseState.not_required': 'neutral',
  'SettlementFailureCode.route_not_ready': 'danger',
  'SettlementFailureCode.balance_mismatch': 'danger',
  'SettlementFailureCode.simulation_reverted': 'danger',
  'SettlementFailureCode.transport_uncertain': 'danger',
  'SettlementFailureCode.submission_rejected': 'danger',
  'SettlementFailureCode.relayer_terminal_failure': 'danger',
  'SettlementFailureCode.on_chain_reverted': 'danger',
  'SettlementFailureCode.receipt_evidence_mismatch': 'danger',
  'SettlementFailureCode.payout_mismatch': 'danger',
  'SettlementFailureCode.deployment_changed': 'danger',
  'SettlementFailureCode.authorization_invalid': 'danger',
  'SettlementFailureCode.execution_not_quiescent': 'danger',
  'SettlementFailureCode.lease_lost': 'danger',
  'SettlementFailureCode.ledger_unavailable': 'danger',
  'SettlementFailureCode.local_invariant': 'danger',
  'SettlementFailureCode.external_evidence_incomplete': 'danger',
  'SettlementGovernedActionState.authorized': 'success',
  'SettlementGovernedActionState.retry_scheduled': 'warning',
  'SettlementGovernedActionState.consumed': 'success',
  'SettlementGovernedActionState.revoked': 'danger',
  'SettlementGovernedActionState.expired': 'neutral',
  'SettlementGovernedActionState.reconciliation_required': 'warning',
  'SettlementGovernedActionState.failed': 'danger',
  'SettlementReadinessStatus.unchecked': 'neutral',
  'SettlementReadinessStatus.ready': 'success',
  'SettlementReadinessStatus.blocked': 'warning',
  'SettlementReconciliationState.not_required': 'neutral',
  'SettlementReconciliationState.awaiting_relayer_hash': 'running',
  'SettlementReconciliationState.awaiting_receipt': 'running',
  'SettlementReconciliationState.evidence_mismatch': 'danger',
  'SettlementReconciliationState.operator_review_required': 'warning',
  'SettlementReconciliationState.reconciled': 'success',
  'SettlementSubmissionState.prepared': 'queued',
  'SettlementSubmissionState.dispatching': 'running',
  'SettlementSubmissionState.awaiting_chain_hash': 'running',
  'SettlementSubmissionState.awaiting_finality': 'running',
  'SettlementSubmissionState.confirmed': 'success',
  'SettlementSubmissionState.failed': 'danger',
  'ShadowBindingStatus.active': 'success',
  'ShadowBindingStatus.rejected': 'danger',
  'ShadowBindingStatus.promoted': 'success',
  'ShadowBindingStatus.cancelled': 'neutral',
  'TradePolicyStatus.draft': 'queued',
  'TradePolicyStatus.validated': 'success',
  'TradePolicyStatus.published': 'success',
  'TradePolicyStatus.retired': 'neutral',
  'VenueOrderStatus.filled': 'success',
  'VenueOrderStatus.partially_filled': 'running',
  'VenueOrderStatus.rejected': 'danger',
  'VenueOrderStatus.cancelled': 'neutral',
  'VenueOrderStatus.open': 'running',
  'VenueOrderStatus.expired': 'neutral',
  'VenueTradeStatus.matched': 'running',
  'VenueTradeStatus.mined': 'running',
  'VenueTradeStatus.confirmed': 'success',
  'VenueTradeStatus.retrying': 'running',
  'VenueTradeStatus.failed': 'danger',
} as const satisfies Partial<Record<EnumMemberKey, SemanticEnumTone>>;

function semanticPresentations() {
  return Object.fromEntries(
    Object.entries(SEMANTIC_ENUM_TONES).map(([key, tone]) => [
      key,
      SEMANTIC_TONE_PRESETS[tone],
    ]),
  ) as {
    [Key in keyof typeof SEMANTIC_ENUM_TONES]: EnumPresentation;
  };
}

/**
 * Exhaustive categorical baseline. Rust catalog changes fail TypeScript
 * compilation until every new member receives an intentional presentation;
 * lifecycle/result members are then overridden by the semantic map above.
 */
const GENERATED_ENUM_PRESENTATION = {
  'AccountSource.polymarket': { categoryHue: 8, tone: 'category' },
  'AccountSource.historical_replay': { categoryHue: 10, tone: 'category' },
  'AdmissionCheckId.intent_state': { categoryHue: 8, tone: 'category' },
  'AdmissionCheckId.recommendation_freshness': {
    categoryHue: 1,
    tone: 'category',
  },
  'AdmissionCheckId.report_status': { categoryHue: 5, tone: 'category' },
  'AdmissionCheckId.runtime_mode': { categoryHue: 6, tone: 'category' },
  'AdmissionCheckId.settlement_recovery': { categoryHue: 7, tone: 'category' },
  'AdmissionCheckId.model_route_binding': { categoryHue: 1, tone: 'category' },
  'AdmissionCheckId.data_quality': { categoryHue: 2, tone: 'category' },
  'AdmissionCheckId.book_freshness': { categoryHue: 11, tone: 'category' },
  'AdmissionCheckId.venue_metadata': { categoryHue: 7, tone: 'category' },
  'AdmissionCheckId.entry_condition': { categoryHue: 12, tone: 'category' },
  'AdmissionCheckId.risk_envelope_hash': { categoryHue: 11, tone: 'category' },
  'AdmissionCheckId.capital_budget': { categoryHue: 12, tone: 'category' },
  'AdmissionCheckId.max_open_intents': { categoryHue: 9, tone: 'category' },
  'AdmissionCheckId.max_reserved_capital': {
    categoryHue: 12,
    tone: 'category',
  },
  'AdmissionCheckId.market_exposure': { categoryHue: 10, tone: 'category' },
  'AdmissionCheckId.event_exposure': { categoryHue: 4, tone: 'category' },
  'AdmissionCheckId.category_exposure': { categoryHue: 2, tone: 'category' },
  'AdmissionCheckId.liquidity_depth': { categoryHue: 12, tone: 'category' },
  'AdmissionCheckId.slippage': { categoryHue: 11, tone: 'category' },
  'AdmissionCheckId.manual_block': { categoryHue: 8, tone: 'category' },
  'AdmissionCheckId.kill_switch': { categoryHue: 1, tone: 'category' },
  'AdmissionCheckId.venue_guard': { categoryHue: 9, tone: 'category' },
  'AdmissionCheckId.credential_readiness': { categoryHue: 2, tone: 'category' },
  'AdmissionCheckId.exit_monitor_readiness': {
    categoryHue: 2,
    tone: 'category',
  },
  'AdmissionCheckId.calibrated_return_model': {
    categoryHue: 10,
    tone: 'category',
  },
  'AdmissionOutcome.allow': { icon: 'lucide:circle-check', tone: 'success' },
  'AdmissionOutcome.deny': { categoryHue: 3, tone: 'category' },
  'AdmissionOutcome.defer': {
    emphasis: 'solid',
    icon: 'lucide:triangle-alert',
    tone: 'warning',
  },
  'ApprovalInvalidation.recommendation_expired': {
    icon: 'lucide:circle-minus',
    tone: 'neutral',
  },
  'ApprovalInvalidation.report_superseded': {
    icon: 'lucide:circle-minus',
    tone: 'neutral',
  },
  'ApprovalInvalidation.report_revoked': { categoryHue: 8, tone: 'category' },
  'ApprovalInvalidation.model_version_retired': {
    icon: 'lucide:circle-minus',
    tone: 'neutral',
  },
  'ApprovalInvalidation.runtime_config_changed': {
    categoryHue: 1,
    tone: 'category',
  },
  'ApprovalInvalidation.risk_envelope_mismatch': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'ApprovalInvalidation.data_quality_degraded': {
    emphasis: 'solid',
    icon: 'lucide:triangle-alert',
    tone: 'warning',
  },
  'ApprovalInvalidation.kill_switch_opened': {
    categoryHue: 12,
    tone: 'category',
  },
  'ApprovalInvalidation.intent_expired': {
    icon: 'lucide:circle-minus',
    tone: 'neutral',
  },
  'ApprovalInvalidation.operator_cancelled': {
    icon: 'lucide:circle-minus',
    tone: 'neutral',
  },
  'ApprovalStatus.not_required': { categoryHue: 10, tone: 'category' },
  'ApprovalStatus.pending': { icon: 'lucide:clock-3', tone: 'queued' },
  'ApprovalStatus.approved': { categoryHue: 2, tone: 'category' },
  'ApprovalStatus.rejected': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'ApprovalStatus.expired': { icon: 'lucide:circle-minus', tone: 'neutral' },
  'AttributionArtifactKind.prediction_explanation': {
    categoryHue: 2,
    tone: 'category',
  },
  'AttributionArtifactKind.decision_intervention_replay': {
    categoryHue: 9,
    tone: 'category',
  },
  'AttributionArtifactKind.resolution_outcome_association': {
    categoryHue: 6,
    tone: 'category',
  },
  'AttributionArtifactKind.execution_outcome_association': {
    categoryHue: 10,
    tone: 'category',
  },
  'AttributionArtifactKind.execution_trajectory': {
    categoryHue: 11,
    tone: 'category',
  },
  'AttributionArtifactKind.policy_counterfactual_outcome': {
    categoryHue: 9,
    tone: 'category',
  },
  'AttributionCohort.training': {
    emphasis: 'solid',
    icon: 'lucide:loader-circle',
    tone: 'running',
  },
  'AttributionCohort.evaluation': { categoryHue: 10, tone: 'category' },
  'AttributionCohort.shadow': { categoryHue: 4, tone: 'category' },
  'CalibrationKind.model_score': { categoryHue: 8, tone: 'category' },
  'CalibrationKind.market_price_bias': { categoryHue: 10, tone: 'category' },
  'CalibrationKind.weather_station_lead_bias': {
    categoryHue: 10,
    tone: 'category',
  },
  'CalibrationMethod.isotonic': { categoryHue: 3, tone: 'category' },
  'CalibrationMethod.platt': { categoryHue: 4, tone: 'category' },
  'CapabilityId.control_plane_ready': {
    icon: 'lucide:circle-check',
    tone: 'success',
  },
  'CapabilityId.catalog_baseline_ready': {
    icon: 'lucide:circle-check',
    tone: 'success',
  },
  'CapabilityId.research_capture_enabled': {
    icon: 'lucide:circle-check',
    tone: 'success',
  },
  'CapabilityId.report_generation_eligible': {
    categoryHue: 8,
    tone: 'category',
  },
  'CapabilityId.entry_admission_eligible': { categoryHue: 3, tone: 'category' },
  'CapabilityId.order_submission_eligible': {
    categoryHue: 8,
    tone: 'category',
  },
  'CapabilityId.automatic_parity_eligible': {
    categoryHue: 4,
    tone: 'category',
  },
  'CapabilityReason.control_plane_not_ready': {
    icon: 'lucide:circle-check',
    tone: 'success',
  },
  'CapabilityReason.catalog_baseline_missing': {
    categoryHue: 8,
    tone: 'category',
  },
  'CapabilityReason.operational_phase_blocks_reports': {
    categoryHue: 5,
    tone: 'category',
  },
  'CapabilityReason.runtime_mode_report_only': {
    categoryHue: 4,
    tone: 'category',
  },
  'CapabilityReason.kill_switch_blocks_entries': {
    categoryHue: 9,
    tone: 'category',
  },
  'CapabilityReason.operational_phase_blocks_submission': {
    categoryHue: 2,
    tone: 'category',
  },
  'CapabilityReason.no_serving_evidence': { categoryHue: 2, tone: 'category' },
  'CapitalAllocationState.allocated': { categoryHue: 6, tone: 'category' },
  'CapitalAllocationState.locked': { categoryHue: 7, tone: 'category' },
  'CapitalAllocationState.spent': { categoryHue: 9, tone: 'category' },
  'CapitalAllocationState.released': { categoryHue: 8, tone: 'category' },
  'CapitalAllocationState.impaired': { categoryHue: 12, tone: 'category' },
  'CatalogChangeType.gamma_scan_upsert': { categoryHue: 2, tone: 'category' },
  'CatalogChangeType.gamma_id_recheck_upsert': {
    categoryHue: 2,
    tone: 'category',
  },
  'CatalogChangeType.gamma_confirmed_tombstone': {
    icon: 'lucide:circle-check',
    tone: 'success',
  },
  'CatalogEntityKind.event': { categoryHue: 12, tone: 'category' },
  'CatalogEntityKind.market': { categoryHue: 2, tone: 'category' },
  'CatalogEntityKind.cursor': { categoryHue: 4, tone: 'category' },
  'CatalogFilterReason.inactive': {
    icon: 'lucide:circle-check',
    tone: 'success',
  },
  'CatalogFilterReason.closed': {
    icon: 'lucide:circle-check',
    tone: 'success',
  },
  'CatalogFilterReason.clob_disabled': {
    icon: 'lucide:circle-minus',
    tone: 'neutral',
  },
  'CatalogFilterReason.orders_not_accepted': {
    categoryHue: 6,
    tone: 'category',
  },
  'CatalogRejectionReason.empty_condition_id': {
    categoryHue: 7,
    tone: 'category',
  },
  'CatalogRejectionReason.missing_clob_token_ids': {
    categoryHue: 8,
    tone: 'category',
  },
  'CatalogRejectionReason.not_binary': { categoryHue: 5, tone: 'category' },
  'CatalogRejectionReason.invalid_token_pair': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'CatalogRejectionReason.unsupported_tick_size': {
    categoryHue: 7,
    tone: 'category',
  },
  'CatalogRejectionReason.duplicate_entity_id': {
    categoryHue: 11,
    tone: 'category',
  },
  'CatalogRejectionReason.malformed_entity': {
    categoryHue: 11,
    tone: 'category',
  },
  'CatalogRejectionReason.cursor_protocol_violation': {
    categoryHue: 3,
    tone: 'category',
  },
  'CatalogSyncFailureStage.fetch': { categoryHue: 10, tone: 'category' },
  'CatalogSyncFailureStage.normalize': { categoryHue: 3, tone: 'category' },
  'CatalogSyncFailureStage.persist': { categoryHue: 6, tone: 'category' },
  'CatalogSyncFailureStage.recovery': { categoryHue: 9, tone: 'category' },
  'CatalogSyncKind.baseline': { categoryHue: 11, tone: 'category' },
  'CatalogSyncKind.reconcile': { categoryHue: 8, tone: 'category' },
  'CatalogSyncStatus.committed': { categoryHue: 2, tone: 'category' },
  'CatalogSyncStatus.failed': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'CatalogTimestampQuality.source': { categoryHue: 5, tone: 'category' },
  'CatalogTimestampQuality.commit_time_fallback': {
    categoryHue: 12,
    tone: 'category',
  },
  'CheckOutcome.passed': { icon: 'lucide:circle-check', tone: 'success' },
  'CheckOutcome.failed': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'CheckOutcome.not_applicable': {
    icon: 'lucide:circle-minus',
    tone: 'neutral',
  },
  'ClassicalKind.gradient_boosted_trees': { categoryHue: 10, tone: 'category' },
  'ClassicalKind.random_forest': { categoryHue: 12, tone: 'category' },
  'ClassicalKind.extra_trees': { categoryHue: 7, tone: 'category' },
  'ClassicalKind.logistic_regression': { categoryHue: 9, tone: 'category' },
  'ClassicalKind.ridge': { categoryHue: 2, tone: 'category' },
  'ClassicalKind.lasso': { categoryHue: 9, tone: 'category' },
  'ClassicalKind.elastic_net': { categoryHue: 2, tone: 'category' },
  'CohortCensorReason.resolution_unavailable_at_cutoff': {
    icon: 'lucide:circle-check',
    tone: 'success',
  },
  'CohortCensorReason.execution_outcome_unavailable_at_cutoff': {
    icon: 'lucide:circle-check',
    tone: 'success',
  },
  'CohortExclusionReason.recommendation_not_published': {
    icon: 'lucide:circle-check',
    tone: 'success',
  },
  'CohortExclusionReason.non_primary_report': {
    categoryHue: 8,
    tone: 'category',
  },
  'CohortExclusionReason.outside_frozen_window': {
    categoryHue: 2,
    tone: 'category',
  },
  'CohortExclusionReason.report_only_no_execution_authority': {
    categoryHue: 1,
    tone: 'category',
  },
  'CohortExclusionReason.execution_not_attempted': {
    categoryHue: 6,
    tone: 'category',
  },
  'ConfigAuditAction.config.draft_created': {
    icon: 'lucide:clock-3',
    tone: 'queued',
  },
  'ConfigAuditAction.config.draft_validated': {
    icon: 'lucide:clock-3',
    tone: 'queued',
  },
  'ConfigAuditAction.config.approval_recorded': {
    categoryHue: 7,
    tone: 'category',
  },
  'ConfigAuditAction.config.revision_activated': {
    categoryHue: 4,
    tone: 'category',
  },
  'ConfigAuditAction.config.revision_rolled_back': {
    categoryHue: 1,
    tone: 'category',
  },
  'ConfigResourceKind.recommendation_policy': {
    categoryHue: 10,
    tone: 'category',
  },
  'ConfigResourceKind.execution_risk_policy': {
    categoryHue: 1,
    tone: 'category',
  },
  'ConfigResourceKind.model_routing': { categoryHue: 4, tone: 'category' },
  'ConfigResourceKind.report_schedule': { categoryHue: 10, tone: 'category' },
  'ConfigResourceKind.operations_policy': { categoryHue: 7, tone: 'category' },
  'ConfigResourceKind.execution_automation_policy': {
    categoryHue: 9,
    tone: 'category',
  },
  'DataQualityStatus.fresh': { categoryHue: 11, tone: 'category' },
  'DataQualityStatus.acceptable': { categoryHue: 3, tone: 'category' },
  'DataQualityStatus.degraded': {
    emphasis: 'solid',
    icon: 'lucide:triangle-alert',
    tone: 'warning',
  },
  'DataQualityStatus.stale': {
    emphasis: 'solid',
    icon: 'lucide:triangle-alert',
    tone: 'warning',
  },
  'DataQualityStatus.insufficient': {
    emphasis: 'solid',
    icon: 'lucide:triangle-alert',
    tone: 'warning',
  },
  'DatasetPurpose.training': {
    emphasis: 'solid',
    icon: 'lucide:loader-circle',
    tone: 'running',
  },
  'DatasetPurpose.calibration': { categoryHue: 6, tone: 'category' },
  'DatasetPurpose.evaluation': { categoryHue: 2, tone: 'category' },
  'DatasetPurpose.policy_fit': { categoryHue: 2, tone: 'category' },
  'DecisionPolicySnapshotSource.bootstrap': {
    categoryHue: 5,
    tone: 'category',
  },
  'DecisionPolicySnapshotSource.activation': {
    categoryHue: 7,
    tone: 'category',
  },
  'DecisionPolicySnapshotSource.rollback': { categoryHue: 3, tone: 'category' },
  'DomainFamily.crypto': { categoryHue: 5, tone: 'category' },
  'DomainFamily.weather': { categoryHue: 4, tone: 'category' },
  'DomainMetric.close': { categoryHue: 12, tone: 'category' },
  'DomainSourceExpectationStatus.not_started': {
    categoryHue: 10,
    tone: 'category',
  },
  'DomainSourceExpectationStatus.live': {
    icon: 'lucide:circle-check',
    tone: 'success',
  },
  'DomainSourceExpectationStatus.stale': {
    emphasis: 'solid',
    icon: 'lucide:triangle-alert',
    tone: 'warning',
  },
  'DomainSourceExpectationStatus.credential_blocked': {
    emphasis: 'solid',
    icon: 'lucide:triangle-alert',
    tone: 'warning',
  },
  'DomainSourceExpectationStatus.error': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'DomainSourceExpectationStatus.unsupported': {
    categoryHue: 6,
    tone: 'category',
  },
  'DownsideSource.mfe_mae': { categoryHue: 10, tone: 'category' },
  'EmptyReportReason.empty_selection': { categoryHue: 7, tone: 'category' },
  'EmptyReportReason.insufficient_data_quality': {
    emphasis: 'solid',
    icon: 'lucide:triangle-alert',
    tone: 'warning',
  },
  'EmptyReportReason.portfolio_budget_exhausted': {
    categoryHue: 7,
    tone: 'category',
  },
  'EmptyReportReason.available_cash_exhausted': {
    icon: 'lucide:circle-check',
    tone: 'success',
  },
  'EmptyReportReason.no_positive_signal': { categoryHue: 11, tone: 'category' },
  'EntryConditionAuditAction.created': { categoryHue: 12, tone: 'category' },
  'EntryConditionAuditAction.evaluated': { categoryHue: 3, tone: 'category' },
  'EntryConditionAuditAction.lease_taken_over': {
    categoryHue: 9,
    tone: 'category',
  },
  'EntryConditionAuditAction.claimed': { categoryHue: 3, tone: 'category' },
  'EntryConditionAuditAction.reverted': { categoryHue: 7, tone: 'category' },
  'EntryConditionAuditAction.expired': {
    icon: 'lucide:circle-minus',
    tone: 'neutral',
  },
  'EntryConditionAuditAction.invalidated': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'EntryConditionState.not_required': { categoryHue: 11, tone: 'category' },
  'EntryConditionState.waiting': { categoryHue: 9, tone: 'category' },
  'EntryConditionState.unavailable': {
    icon: 'lucide:circle-check',
    tone: 'success',
  },
  'EntryConditionState.confirming': {
    emphasis: 'solid',
    icon: 'lucide:loader-circle',
    tone: 'running',
  },
  'EntryConditionState.qualified': { categoryHue: 10, tone: 'category' },
  'EntryConditionState.consumed': { categoryHue: 4, tone: 'category' },
  'EntryConditionState.expired': {
    icon: 'lucide:circle-minus',
    tone: 'neutral',
  },
  'EntryConditionState.invalidated': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'EventStatus.active': { icon: 'lucide:circle-check', tone: 'success' },
  'EventStatus.closed': { icon: 'lucide:circle-check', tone: 'success' },
  'EventStatus.archived': { categoryHue: 12, tone: 'category' },
  'EventStatus.unknown': { icon: 'lucide:circle-minus', tone: 'neutral' },
  'ExecutionAttemptNoFillReason.venue_rejected': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'ExecutionAttemptNoFillReason.venue_cancelled': {
    icon: 'lucide:circle-minus',
    tone: 'neutral',
  },
  'ExecutionAttemptNoFillReason.venue_expired': {
    icon: 'lucide:circle-minus',
    tone: 'neutral',
  },
  'ExecutionAttemptNoFillReason.reconciled_not_filled': {
    icon: 'lucide:circle-check',
    tone: 'success',
  },
  'ExecutionAttemptTerminalState.unfilled': {
    icon: 'lucide:circle-check',
    tone: 'success',
  },
  'ExecutionAttemptTerminalState.partially_filled': {
    emphasis: 'solid',
    icon: 'lucide:triangle-alert',
    tone: 'warning',
  },
  'ExecutionAttemptTerminalState.fully_filled': {
    icon: 'lucide:circle-check',
    tone: 'success',
  },
  'ExecutionOrderPhase.entry': { categoryHue: 1, tone: 'category' },
  'ExecutionOrderPhase.exit': { categoryHue: 9, tone: 'category' },
  'ExecutionOrderState.planned': { icon: 'lucide:clock-3', tone: 'queued' },
  'ExecutionOrderState.accepted': { categoryHue: 4, tone: 'category' },
  'ExecutionOrderState.submitted': {
    emphasis: 'solid',
    icon: 'lucide:loader-circle',
    tone: 'running',
  },
  'ExecutionOrderState.partially_filled': {
    emphasis: 'solid',
    icon: 'lucide:triangle-alert',
    tone: 'warning',
  },
  'ExecutionOrderState.filled': {
    icon: 'lucide:circle-check',
    tone: 'success',
  },
  'ExecutionOrderState.cancel_requested': {
    icon: 'lucide:clock-3',
    tone: 'queued',
  },
  'ExecutionOrderState.cancelled': {
    icon: 'lucide:circle-minus',
    tone: 'neutral',
  },
  'ExecutionOrderState.failed': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'ExecutionOrderState.ambiguous': {
    emphasis: 'solid',
    icon: 'lucide:triangle-alert',
    tone: 'warning',
  },
  'ExecutionWalletKind.eoa': { categoryHue: 8, tone: 'category' },
  'ExecutionWalletKind.proxy': { categoryHue: 1, tone: 'category' },
  'ExecutionWalletKind.gnosis_safe': { categoryHue: 10, tone: 'category' },
  'ExecutionWalletKind.deposit_wallet': { categoryHue: 3, tone: 'category' },
  'ExitReason.take_profit': { categoryHue: 6, tone: 'category' },
  'ExitReason.stop_loss': { categoryHue: 6, tone: 'category' },
  'ExitReason.time_exit': { categoryHue: 2, tone: 'category' },
  'ExitReason.partial_exit': {
    emphasis: 'solid',
    icon: 'lucide:triangle-alert',
    tone: 'warning',
  },
  'ExitReason.signal_invalidated': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'ExitReason.opportunistic': { categoryHue: 3, tone: 'category' },
  'ExitReason.manual': { categoryHue: 4, tone: 'category' },
  'ExitReason.settlement_hold': { categoryHue: 11, tone: 'category' },
  'ExitReason.resolution_redeem': { categoryHue: 1, tone: 'category' },
  'ExitReason.kill_switch_emergency': { categoryHue: 9, tone: 'category' },
  'ExitReason.risk_envelope_breached': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'ExitReason.market_abnormal': { categoryHue: 3, tone: 'category' },
  'ExitReason.data_stale': {
    emphasis: 'solid',
    icon: 'lucide:triangle-alert',
    tone: 'warning',
  },
  'ExitSettlementMode.hold_to_resolution': { categoryHue: 8, tone: 'category' },
  'ExitSettlementMode.exit_before_resolution': {
    categoryHue: 1,
    tone: 'category',
  },
  'ExitState.not_started': { categoryHue: 4, tone: 'category' },
  'ExitState.monitoring': { categoryHue: 7, tone: 'category' },
  'ExitState.triggered': { categoryHue: 6, tone: 'category' },
  'ExitState.order_submitted': {
    emphasis: 'solid',
    icon: 'lucide:loader-circle',
    tone: 'running',
  },
  'ExitState.partially_exited': {
    emphasis: 'solid',
    icon: 'lucide:triangle-alert',
    tone: 'warning',
  },
  'ExitState.exited': { categoryHue: 2, tone: 'category' },
  'ExitState.failed': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'ExitState.manual_required': {
    emphasis: 'solid',
    icon: 'lucide:triangle-alert',
    tone: 'warning',
  },
  'FactorDefinitionScope.generic': { categoryHue: 7, tone: 'category' },
  'FactorDefinitionScope.structural': { categoryHue: 11, tone: 'category' },
  'FactorDefinitionScope.domain_crypto': { categoryHue: 12, tone: 'category' },
  'FactorDefinitionScope.domain_weather': { categoryHue: 3, tone: 'category' },
  'FactorDirection.positive': { categoryHue: 9, tone: 'category' },
  'FactorDirection.negative': { categoryHue: 9, tone: 'category' },
  'FactorDirection.neutral': { categoryHue: 3, tone: 'category' },
  'FactorFamily.liquidity': { categoryHue: 1, tone: 'category' },
  'FactorFamily.microstructure': { categoryHue: 2, tone: 'category' },
  'FactorFamily.momentum': { categoryHue: 7, tone: 'category' },
  'FactorFamily.mean_reversion': { categoryHue: 6, tone: 'category' },
  'FactorFamily.volatility': { categoryHue: 12, tone: 'category' },
  'FactorFamily.activity': { categoryHue: 2, tone: 'category' },
  'FactorFamily.resolution': { categoryHue: 7, tone: 'category' },
  'FactorFamily.data_quality': { categoryHue: 3, tone: 'category' },
  'FactorFamily.structural': { categoryHue: 12, tone: 'category' },
  'FactorFamily.domain_crypto': { categoryHue: 1, tone: 'category' },
  'FactorFamily.domain_weather': { categoryHue: 12, tone: 'category' },
  'FactorIndeterminateReason.cross_section_too_small': {
    categoryHue: 3,
    tone: 'category',
  },
  'FactorIndeterminateReason.zero_variance': {
    categoryHue: 8,
    tone: 'category',
  },
  'FactorIndeterminateReason.no_frozen_reference': {
    categoryHue: 8,
    tone: 'category',
  },
  'FactorIndeterminateReason.leg_book_missing': {
    categoryHue: 7,
    tone: 'category',
  },
  'FactorNormalization.winsorized_zscore': { categoryHue: 1, tone: 'category' },
  'FactorNormalization.rank': { categoryHue: 6, tone: 'category' },
  'FactorNormalization.min_max': { categoryHue: 1, tone: 'category' },
  'FactorValueState.scored': { categoryHue: 1, tone: 'category' },
  'FactorValueState.missing_input': { categoryHue: 2, tone: 'category' },
  'FactorValueState.not_applicable': {
    icon: 'lucide:circle-minus',
    tone: 'neutral',
  },
  'FactorValueState.indeterminate': { categoryHue: 6, tone: 'category' },
  'FeatureCellState.observed': { categoryHue: 9, tone: 'category' },
  'FeatureCellState.substituted': { categoryHue: 9, tone: 'category' },
  'FeatureCellState.missing': { categoryHue: 9, tone: 'category' },
  'FeatureCellState.not_applicable': {
    icon: 'lucide:circle-minus',
    tone: 'neutral',
  },
  'FeatureParityEventStatus.matched': {
    icon: 'lucide:circle-check',
    tone: 'success',
  },
  'FeatureParityEventStatus.mismatched': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'FeatureParityEventStatus.pending_materialization': {
    icon: 'lucide:clock-3',
    tone: 'queued',
  },
  'FeatureParityLatchState.open': { categoryHue: 12, tone: 'category' },
  'FeatureParityLatchState.clear': { categoryHue: 1, tone: 'category' },
  'FeatureParityRunKind.sampled': { categoryHue: 12, tone: 'category' },
  'FeatureParityRunKind.full': { categoryHue: 7, tone: 'category' },
  'FeatureParityRunStatus.queued': { icon: 'lucide:clock-3', tone: 'queued' },
  'FeatureParityRunStatus.running': {
    emphasis: 'solid',
    icon: 'lucide:loader-circle',
    tone: 'running',
  },
  'FeatureParityRunStatus.pending_materialization': {
    icon: 'lucide:clock-3',
    tone: 'queued',
  },
  'FeatureParityRunStatus.passed': {
    icon: 'lucide:circle-check',
    tone: 'success',
  },
  'FeatureParityRunStatus.mismatched': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'FeatureParityRunStatus.failed': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'FeatureParityStage.selection': { categoryHue: 7, tone: 'category' },
  'FeatureParityStage.snapshot': { categoryHue: 5, tone: 'category' },
  'FeatureParityStage.capture': { categoryHue: 7, tone: 'category' },
  'FeatureParityStage.feature_cell': { categoryHue: 12, tone: 'category' },
  'FeatureParityStage.data_quality': { categoryHue: 7, tone: 'category' },
  'FeatureParityStage.factor': { categoryHue: 8, tone: 'category' },
  'FeatureParityStage.model_input': { categoryHue: 7, tone: 'category' },
  'FeatureParityStage.prediction': { categoryHue: 10, tone: 'category' },
  'FeatureParityStateTransition.bootstrap_proof': {
    categoryHue: 4,
    tone: 'category',
  },
  'FeatureParityStateTransition.deterministic_mismatch': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'FeatureParityStateTransition.integrity_failure': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'FeatureParityStateTransition.governed_acknowledge': {
    categoryHue: 6,
    tone: 'category',
  },
  'FeedbackCohort.model_learning': { categoryHue: 12, tone: 'category' },
  'FeedbackCohort.model_score_learning': { categoryHue: 1, tone: 'category' },
  'FeedbackCohort.execution_learning': { categoryHue: 7, tone: 'category' },
  'FeedbackCohort.policy_evaluation': { categoryHue: 1, tone: 'category' },
  'FeedbackCycleStatus.queued': { icon: 'lucide:clock-3', tone: 'queued' },
  'FeedbackCycleStatus.running': {
    emphasis: 'solid',
    icon: 'lucide:loader-circle',
    tone: 'running',
  },
  'FeedbackCycleStatus.succeeded': {
    icon: 'lucide:circle-check',
    tone: 'success',
  },
  'FeedbackCycleStatus.failed': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'FeedbackCycleStatus.cancelled': {
    icon: 'lucide:circle-minus',
    tone: 'neutral',
  },
  'FeedbackCycleStatus.quarantined': { categoryHue: 9, tone: 'category' },
  'FeedbackDecision.no_action': { categoryHue: 9, tone: 'category' },
  'FeedbackDecision.challenger_rejected': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'FeedbackDecision.candidate_ready': {
    icon: 'lucide:clock-3',
    tone: 'queued',
  },
  'FeedbackDecision.promoted': { categoryHue: 11, tone: 'category' },
  'FeedbackDriftAssessment.within_threshold': {
    categoryHue: 9,
    tone: 'category',
  },
  'FeedbackDriftAssessment.threshold_exceeded': {
    categoryHue: 7,
    tone: 'category',
  },
  'FeedbackDriftAssessment.insufficient_evidence': {
    emphasis: 'solid',
    icon: 'lucide:triangle-alert',
    tone: 'warning',
  },
  'FeedbackDriftKind.data': { categoryHue: 4, tone: 'category' },
  'FeedbackDriftKind.concept': { categoryHue: 6, tone: 'category' },
  'FeedbackDriftKind.label': { categoryHue: 4, tone: 'category' },
  'FeedbackDriftMetric.population_stability_index': {
    categoryHue: 10,
    tone: 'category',
  },
  'FeedbackDriftMetric.kolmogorov_smirnov_p_value': {
    categoryHue: 7,
    tone: 'category',
  },
  'FeedbackDriftMetric.rank_ic_drop': { categoryHue: 1, tone: 'category' },
  'FeedbackDriftMetric.jensen_shannon_divergence': {
    categoryHue: 8,
    tone: 'category',
  },
  'FeedbackEvaluationMode.conditional': { categoryHue: 2, tone: 'category' },
  'FeedbackEvaluationMode.forced_retraining': {
    emphasis: 'solid',
    icon: 'lucide:loader-circle',
    tone: 'running',
  },
  'FeedbackEvaluationPurpose.promotion_comparison': {
    categoryHue: 8,
    tone: 'category',
  },
  'FeedbackRecipeTemplateStatus.draft': {
    icon: 'lucide:clock-3',
    tone: 'queued',
  },
  'FeedbackRecipeTemplateStatus.approved': { categoryHue: 6, tone: 'category' },
  'FeedbackRecipeTemplateStatus.retired': {
    icon: 'lucide:circle-minus',
    tone: 'neutral',
  },
  'FeedbackSchedulerFailureKind.materialization': {
    categoryHue: 9,
    tone: 'category',
  },
  'FeedbackSchedulerFailureKind.settlement': {
    categoryHue: 7,
    tone: 'category',
  },
  'FeedbackStage.trigger': { categoryHue: 7, tone: 'category' },
  'FeedbackStage.truth_freeze': { categoryHue: 12, tone: 'category' },
  'FeedbackStage.coverage': { categoryHue: 9, tone: 'category' },
  'FeedbackStage.attribution': { categoryHue: 12, tone: 'category' },
  'FeedbackStage.drift': { categoryHue: 6, tone: 'category' },
  'FeedbackStage.recipe_plan': { categoryHue: 3, tone: 'category' },
  'FeedbackStage.dataset_seal': { categoryHue: 7, tone: 'category' },
  'FeedbackStage.training': {
    emphasis: 'solid',
    icon: 'lucide:loader-circle',
    tone: 'running',
  },
  'FeedbackStage.calibration': { categoryHue: 11, tone: 'category' },
  'FeedbackStage.cpcv': { categoryHue: 1, tone: 'category' },
  'FeedbackStage.validation': { categoryHue: 6, tone: 'category' },
  'FeedbackStage.comparison': { categoryHue: 12, tone: 'category' },
  'FeedbackStage.shadow_bind': { categoryHue: 9, tone: 'category' },
  'FeedbackStage.shadow': { categoryHue: 11, tone: 'category' },
  'FeedbackStage.decision': { categoryHue: 9, tone: 'category' },
  'FeedbackStageEventKind.triggered': { categoryHue: 2, tone: 'category' },
  'FeedbackStageEventKind.job_linked': { categoryHue: 2, tone: 'category' },
  'FeedbackStageEventKind.started': { categoryHue: 6, tone: 'category' },
  'FeedbackStageEventKind.succeeded': {
    icon: 'lucide:circle-check',
    tone: 'success',
  },
  'FeedbackStageEventKind.failed': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'FeedbackStageEventKind.cancellation_requested': {
    icon: 'lucide:clock-3',
    tone: 'queued',
  },
  'FeedbackStageEventKind.cancelled': {
    icon: 'lucide:circle-minus',
    tone: 'neutral',
  },
  'FeedbackStageEventKind.lease_recovered': {
    categoryHue: 5,
    tone: 'category',
  },
  'FeedbackTriggerFamily.scheduled': { icon: 'lucide:clock-3', tone: 'queued' },
  'FeedbackTriggerFamily.manual': { categoryHue: 11, tone: 'category' },
  'FillRequirement.all_or_nothing': { categoryHue: 5, tone: 'category' },
  'FillRequirement.allow_partial': {
    emphasis: 'solid',
    icon: 'lucide:triangle-alert',
    tone: 'warning',
  },
  'IneligibilityReason.report_only_mode': { categoryHue: 7, tone: 'category' },
  'IneligibilityReason.automation_cap_exceeded': {
    categoryHue: 2,
    tone: 'category',
  },
  'KillSwitchState.closed': { icon: 'lucide:circle-check', tone: 'success' },
  'KillSwitchState.execution_halted': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'KillSwitchState.exit_only': { categoryHue: 12, tone: 'category' },
  'KillSwitchState.emergency_halted': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'KlineInterval.1m': { categoryHue: 4, tone: 'category' },
  'KlineInterval.1h': { categoryHue: 1, tone: 'category' },
  'LinkageSourceRole.feature': { categoryHue: 10, tone: 'category' },
  'LinkageSourceRole.live_event': {
    icon: 'lucide:circle-check',
    tone: 'success',
  },
  'LinkageSourceRole.resolution': { categoryHue: 8, tone: 'category' },
  'LinkageSourceRole.historical_calibration': {
    categoryHue: 3,
    tone: 'category',
  },
  'LinkageSourceRole.forecast': { categoryHue: 5, tone: 'category' },
  'LinkageStatus.resolved': { icon: 'lucide:circle-check', tone: 'success' },
  'LinkageStatus.unresolved': { icon: 'lucide:circle-check', tone: 'success' },
  'LinkageStatus.overridden': { categoryHue: 5, tone: 'category' },
  'MarketCategory.geopolitics': { categoryHue: 6, tone: 'category' },
  'MarketCategory.sports': { categoryHue: 3, tone: 'category' },
  'MarketCategory.politics': { categoryHue: 7, tone: 'category' },
  'MarketCategory.finance': { categoryHue: 10, tone: 'category' },
  'MarketCategory.tech': { categoryHue: 10, tone: 'category' },
  'MarketCategory.culture': { categoryHue: 10, tone: 'category' },
  'MarketCategory.weather': { categoryHue: 4, tone: 'category' },
  'MarketCategory.economics': { categoryHue: 10, tone: 'category' },
  'MarketCategory.crypto': { categoryHue: 5, tone: 'category' },
  'MarketCategory.other': { categoryHue: 10, tone: 'category' },
  'MarketStatus.discovered': { categoryHue: 2, tone: 'category' },
  'MarketStatus.active': { icon: 'lucide:circle-check', tone: 'success' },
  'MarketStatus.filtered': { categoryHue: 5, tone: 'category' },
  'MarketStatus.paused': { icon: 'lucide:pause-circle', tone: 'paused' },
  'MarketStatus.manually_blocked': {
    emphasis: 'solid',
    icon: 'lucide:triangle-alert',
    tone: 'warning',
  },
  'MarketStatus.settled': { icon: 'lucide:circle-check', tone: 'success' },
  'MarketStatus.delisted': { categoryHue: 6, tone: 'category' },
  'MenuKind.directory': { categoryHue: 2, tone: 'category' },
  'MenuKind.menu': { categoryHue: 2, tone: 'category' },
  'MenuKind.button': { categoryHue: 11, tone: 'category' },
  'ModeDenialReason.report_only': { categoryHue: 7, tone: 'category' },
  'ModeDenialReason.recommendation_ineligible': {
    categoryHue: 2,
    tone: 'category',
  },
  'ModeDenialReason.risk_envelope_invalid': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'ModeDenialReason.kill_switch_blocks_entry': {
    categoryHue: 11,
    tone: 'category',
  },
  'ModeDenialReason.auto_execution_not_allowed': {
    icon: 'lucide:circle-check',
    tone: 'success',
  },
  'ModelFamily.weighted_factor': { categoryHue: 2, tone: 'category' },
  'ModelFamily.classical_gradient_boosted_trees': {
    categoryHue: 10,
    tone: 'category',
  },
  'ModelFamily.classical_random_forest': { categoryHue: 4, tone: 'category' },
  'ModelFamily.classical_extra_trees': { categoryHue: 3, tone: 'category' },
  'ModelFamily.classical_logistic_regression': {
    categoryHue: 9,
    tone: 'category',
  },
  'ModelFamily.classical_ridge': { categoryHue: 2, tone: 'category' },
  'ModelFamily.classical_lasso': { categoryHue: 1, tone: 'category' },
  'ModelFamily.classical_elastic_net': { categoryHue: 10, tone: 'category' },
  'ModelFamily.hold_vs_exit_weighted': { categoryHue: 3, tone: 'category' },
  'ModelGovernanceAction.bootstrap_route': { categoryHue: 3, tone: 'category' },
  'ModelGovernanceAction.promote_route': { categoryHue: 5, tone: 'category' },
  'ModelGovernanceAction.seal_calibration': {
    categoryHue: 5,
    tone: 'category',
  },
  'ModelRunErrorCode.active_inference_failed': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'ModelRunErrorCode.shadow_inference_failed': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'ModelRunErrorCode.feature_plane_failed': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'ModelRunErrorCode.factor_plane_failed': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'ModelRunErrorCode.selection_failed': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'ModelRunErrorCode.artifact_load_failed': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'ModelRunErrorCode.schema_binding_failed': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'ModelRunErrorCode.training_failed': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'ModelRunErrorCode.calibration_failed': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'ModelRunErrorCode.cancelled_by_operator': {
    icon: 'lucide:circle-minus',
    tone: 'neutral',
  },
  'ModelRunKind.training': {
    emphasis: 'solid',
    icon: 'lucide:loader-circle',
    tone: 'running',
  },
  'ModelRunKind.backtest': { categoryHue: 3, tone: 'category' },
  'ModelRunKind.calibration': { categoryHue: 8, tone: 'category' },
  'ModelRunKind.cpcv': { categoryHue: 4, tone: 'category' },
  'ModelRunKind.shadow': { categoryHue: 2, tone: 'category' },
  'ModelRunKind.live_inference': {
    icon: 'lucide:circle-check',
    tone: 'success',
  },
  'ModelRunStatus.running': {
    emphasis: 'solid',
    icon: 'lucide:loader-circle',
    tone: 'running',
  },
  'ModelRunStatus.succeeded': { icon: 'lucide:circle-check', tone: 'success' },
  'ModelRunStatus.failed': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'ModelRunStatus.cancelled': { icon: 'lucide:circle-minus', tone: 'neutral' },
  'ModelSerializationFormat.json': { categoryHue: 8, tone: 'category' },
  'ModelSerializationFormat.bincode': { categoryHue: 8, tone: 'category' },
  'ModelVersionDerivationKind.training': {
    emphasis: 'solid',
    icon: 'lucide:loader-circle',
    tone: 'running',
  },
  'ModelVersionDerivationKind.return_calibration': {
    categoryHue: 1,
    tone: 'category',
  },
  'ModelWeightSource.artifact': { categoryHue: 2, tone: 'category' },
  'NormalizationSource.cross_section': { categoryHue: 6, tone: 'category' },
  'NormalizationSource.per_market': { categoryHue: 4, tone: 'category' },
  'NormalizationSource.frozen_reference_quantile': {
    categoryHue: 6,
    tone: 'category',
  },
  'OperationCategory.auth': { categoryHue: 3, tone: 'category' },
  'OperationCategory.rbac': { categoryHue: 9, tone: 'category' },
  'OperationCategory.governance': { categoryHue: 1, tone: 'category' },
  'OperationCategory.config': { categoryHue: 3, tone: 'category' },
  'OperationCategory.system': { categoryHue: 6, tone: 'category' },
  'OperationCategory.risk': { categoryHue: 4, tone: 'category' },
  'OperationCategory.quant_report': { categoryHue: 7, tone: 'category' },
  'OperationCategory.market': { categoryHue: 1, tone: 'category' },
  'OperationCategory.replay': { categoryHue: 8, tone: 'category' },
  'OperationCategory.other': { categoryHue: 7, tone: 'category' },
  'OperationHttpMethod.GET': { categoryHue: 2, tone: 'category' },
  'OperationHttpMethod.POST': { categoryHue: 10, tone: 'category' },
  'OperationHttpMethod.PUT': { categoryHue: 5, tone: 'category' },
  'OperationHttpMethod.PATCH': { categoryHue: 12, tone: 'category' },
  'OperationHttpMethod.DELETE': { categoryHue: 1, tone: 'category' },
  'OperationHttpMethod.SYSTEM': { categoryHue: 3, tone: 'category' },
  'OperationOutcome.success': { icon: 'lucide:circle-check', tone: 'success' },
  'OperationOutcome.failure': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'OperationOutcome.denied': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'OrderIntentKind.buy': { categoryHue: 6, tone: 'category' },
  'OrderIntentStatus.draft': { icon: 'lucide:clock-3', tone: 'queued' },
  'OrderIntentStatus.pending_approval': {
    icon: 'lucide:clock-3',
    tone: 'queued',
  },
  'OrderIntentStatus.approved': { categoryHue: 1, tone: 'category' },
  'OrderIntentStatus.approved_by_policy': { categoryHue: 8, tone: 'category' },
  'OrderIntentStatus.admission_pending': {
    icon: 'lucide:clock-3',
    tone: 'queued',
  },
  'OrderIntentStatus.admission_rejected': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'OrderIntentStatus.submitted': {
    emphasis: 'solid',
    icon: 'lucide:loader-circle',
    tone: 'running',
  },
  'OrderIntentStatus.partially_filled': {
    emphasis: 'solid',
    icon: 'lucide:triangle-alert',
    tone: 'warning',
  },
  'OrderIntentStatus.filled': { icon: 'lucide:circle-check', tone: 'success' },
  'OrderIntentStatus.rejected': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'OrderIntentStatus.cancelled': {
    icon: 'lucide:circle-minus',
    tone: 'neutral',
  },
  'OrderIntentStatus.failed': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'OrderIntentStatus.expired': { icon: 'lucide:circle-minus', tone: 'neutral' },
  'OrderIntentStatus.invalidated': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'OrderTypeKind.fok': { categoryHue: 8, tone: 'category' },
  'OrderTypeKind.fak': { categoryHue: 2, tone: 'category' },
  'OrderTypeKind.gtc': { categoryHue: 12, tone: 'category' },
  'OrderTypeKind.gtd': { categoryHue: 7, tone: 'category' },
  'OutcomeReconciliationTaskStatus.pending': {
    icon: 'lucide:clock-3',
    tone: 'queued',
  },
  'OutcomeReconciliationTaskStatus.delivering': {
    icon: 'lucide:circle-check',
    tone: 'success',
  },
  'OutcomeReconciliationTaskStatus.retrying': {
    categoryHue: 8,
    tone: 'category',
  },
  'OutcomeReconciliationTaskStatus.completed': {
    icon: 'lucide:circle-check',
    tone: 'success',
  },
  'OutcomeSide.yes': { categoryHue: 2, tone: 'category' },
  'OutcomeSide.no': { categoryHue: 2, tone: 'category' },
  'ParitySubjectKind.recommendation_report': {
    categoryHue: 3,
    tone: 'category',
  },
  'ParitySubjectKind.model_run': { categoryHue: 12, tone: 'category' },
  'ParitySubjectKind.model_version': { categoryHue: 11, tone: 'category' },
  'PolicyActivationKind.initial': { categoryHue: 4, tone: 'category' },
  'PolicyActivationKind.promote': { categoryHue: 8, tone: 'category' },
  'PolicyActivationKind.model_bootstrap': { categoryHue: 4, tone: 'category' },
  'PolicyActivationKind.model_shadow_binding': {
    categoryHue: 6,
    tone: 'category',
  },
  'PolicyActivationKind.model_shadow_cancellation': {
    categoryHue: 8,
    tone: 'category',
  },
  'PolicyActivationKind.model_shadow_rejection': {
    categoryHue: 12,
    tone: 'category',
  },
  'PolicyActivationKind.model_promotion': { categoryHue: 5, tone: 'category' },
  'PolicyActivationKind.rollback': { categoryHue: 2, tone: 'category' },
  'PolicyActorKind.operator': { categoryHue: 1, tone: 'category' },
  'PolicyActorKind.system': { categoryHue: 2, tone: 'category' },
  'PolicyApplyBoundary.report_run_claim': { categoryHue: 5, tone: 'category' },
  'PolicyApplyBoundary.order_intent_creation': {
    categoryHue: 5,
    tone: 'category',
  },
  'PolicyApplyBoundary.model_evaluation_claim': {
    categoryHue: 9,
    tone: 'category',
  },
  'PolicyApplyBoundary.future_report_run_reconcile': {
    categoryHue: 11,
    tone: 'category',
  },
  'PolicyApplyBoundary.operational_admission': {
    categoryHue: 4,
    tone: 'category',
  },
  'PolicyApplyBoundary.execution_automation_policy_admission': {
    categoryHue: 9,
    tone: 'category',
  },
  'PolicyApprovalDecision.approved': { categoryHue: 12, tone: 'category' },
  'PolicyApprovalDecision.rejected': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'PolicyConsumer.market_selection': { categoryHue: 7, tone: 'category' },
  'PolicyConsumer.report_coordinator': { categoryHue: 5, tone: 'category' },
  'PolicyConsumer.recommendation_composer': {
    categoryHue: 8,
    tone: 'category',
  },
  'PolicyConsumer.data_quality_gate': { categoryHue: 10, tone: 'category' },
  'PolicyConsumer.portfolio_optimizer': { categoryHue: 10, tone: 'category' },
  'PolicyConsumer.order_intent_service': { categoryHue: 9, tone: 'category' },
  'PolicyConsumer.execution_admission': { categoryHue: 2, tone: 'category' },
  'PolicyConsumer.exit_monitor': { categoryHue: 7, tone: 'category' },
  'PolicyConsumer.model_runner': { categoryHue: 8, tone: 'category' },
  'PolicyConsumer.report_scheduler': { categoryHue: 12, tone: 'category' },
  'PolicyConsumer.worker_admission': { categoryHue: 4, tone: 'category' },
  'PolicyConsumer.alert_dispatcher': { categoryHue: 2, tone: 'category' },
  'PolicyConsumer.runtime_mode_gate': { categoryHue: 2, tone: 'category' },
  'PolicyPreflightCheckKind.typed_schema': { categoryHue: 5, tone: 'category' },
  'PolicyPreflightCheckKind.semantic_validation': {
    categoryHue: 5,
    tone: 'category',
  },
  'PolicyPreflightCheckKind.consumer_preparation': {
    categoryHue: 9,
    tone: 'category',
  },
  'PolicyPreflightCheckKind.artifact_compatibility': {
    categoryHue: 12,
    tone: 'category',
  },
  'PolicyPreflightCheckKind.credential_availability': {
    categoryHue: 4,
    tone: 'category',
  },
  'PolicyPreflightCheckKind.schedule_preview': {
    icon: 'lucide:clock-3',
    tone: 'queued',
  },
  'PolicyPreflightCheckKind.execution_capability': {
    categoryHue: 12,
    tone: 'category',
  },
  'PolicyPreflightDetailCode.typed_document_decoded': {
    categoryHue: 2,
    tone: 'category',
  },
  'PolicyPreflightDetailCode.semantic_validation_passed': {
    icon: 'lucide:circle-check',
    tone: 'success',
  },
  'PolicyPreflightDetailCode.semantic_validation_failed': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'PolicyPreflightDetailCode.consumer_preparation_passed': {
    icon: 'lucide:circle-check',
    tone: 'success',
  },
  'PolicyPreflightDetailCode.consumer_preparation_skipped': {
    icon: 'lucide:circle-minus',
    tone: 'neutral',
  },
  'PolicyPreflightDetailCode.consumer_preparation_failed': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'PolicyRevisionStatus.draft': { icon: 'lucide:clock-3', tone: 'queued' },
  'PolicyRevisionStatus.validated': { categoryHue: 1, tone: 'category' },
  'PolicyValidationCode.schema_version_mismatch': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'PolicyValidationCode.resource_kind_mismatch': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'PolicyValidationCode.semantic_constraint': {
    categoryHue: 10,
    tone: 'category',
  },
  'PolicyValidationCode.dependency_unavailable': {
    icon: 'lucide:circle-check',
    tone: 'success',
  },
  'PolicyValidationCode.artifact_incompatible': {
    categoryHue: 10,
    tone: 'category',
  },
  'PolicyValidationCode.credential_unavailable': {
    icon: 'lucide:circle-check',
    tone: 'success',
  },
  'PolicyValidationCode.schedule_invalid': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'PolicyValidationCode.authorization_denied': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'PolicyValidationSeverity.error': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'PolicyValidationSeverity.warning': {
    emphasis: 'solid',
    icon: 'lucide:triangle-alert',
    tone: 'warning',
  },
  'PositionLedgerState.open': { categoryHue: 11, tone: 'category' },
  'PositionLedgerState.closing': { categoryHue: 10, tone: 'category' },
  'PositionLedgerState.closed': {
    icon: 'lucide:circle-check',
    tone: 'success',
  },
  'PositionLedgerState.settled': {
    icon: 'lucide:circle-check',
    tone: 'success',
  },
  'PriceComparison.at_or_above': { categoryHue: 9, tone: 'category' },
  'PriceComparison.at_or_below': { categoryHue: 9, tone: 'category' },
  'ProfileArtifactKind.feature': { categoryHue: 3, tone: 'category' },
  'ProfileArtifactKind.scoring': { categoryHue: 6, tone: 'category' },
  'ProfileArtifactKind.domain': { categoryHue: 9, tone: 'category' },
  'ProfileArtifactKind.research_method': { categoryHue: 4, tone: 'category' },
  'QuantRuntimeMode.report_only': { categoryHue: 5, tone: 'category' },
  'QuantRuntimeMode.semi_auto': { categoryHue: 2, tone: 'category' },
  'QuantRuntimeMode.auto_execution': { categoryHue: 10, tone: 'category' },
  'RecommendationReportStatus.prepared': {
    icon: 'lucide:clock-3',
    tone: 'queued',
  },
  'RecommendationReportStatus.published': {
    icon: 'lucide:circle-check',
    tone: 'success',
  },
  'RecommendationReportStatus.superseded': {
    icon: 'lucide:circle-minus',
    tone: 'neutral',
  },
  'RecommendationReportStatus.obsolete': {
    icon: 'lucide:circle-minus',
    tone: 'neutral',
  },
  'RecommendationReportStatus.revoked': { categoryHue: 3, tone: 'category' },
  'RecommendationReportStatus.expired': {
    icon: 'lucide:circle-minus',
    tone: 'neutral',
  },
  'RecommendationResolutionKind.winner_take_all': {
    categoryHue: 4,
    tone: 'category',
  },
  'RecommendationResolutionKind.split_payout': {
    categoryHue: 12,
    tone: 'category',
  },
  'RecommendationStatus.prepared': { icon: 'lucide:clock-3', tone: 'queued' },
  'RecommendationStatus.published': {
    icon: 'lucide:circle-check',
    tone: 'success',
  },
  'RecommendationStatus.superseded': {
    icon: 'lucide:circle-minus',
    tone: 'neutral',
  },
  'RecommendationStatus.obsolete': {
    icon: 'lucide:circle-minus',
    tone: 'neutral',
  },
  'RecommendationStatus.revoked': { categoryHue: 5, tone: 'category' },
  'RecommendationStatus.expired': {
    icon: 'lucide:circle-minus',
    tone: 'neutral',
  },
  'RecommendationStatus.intent_created': { categoryHue: 4, tone: 'category' },
  'RecommendationStatus.executed': { categoryHue: 12, tone: 'category' },
  'ReconciliationEvidenceKind.clob_order_status': {
    categoryHue: 10,
    tone: 'category',
  },
  'ReconciliationEvidenceKind.clob_trades': {
    categoryHue: 6,
    tone: 'category',
  },
  'ReconciliationEvidenceKind.token_balance_delta': {
    categoryHue: 3,
    tone: 'category',
  },
  'ReconciliationEvidenceKind.account_balance_delta': {
    categoryHue: 1,
    tone: 'category',
  },
  'ReconciliationEvidenceKind.book_context': {
    categoryHue: 3,
    tone: 'category',
  },
  'ReconciliationEvidenceKind.operator_note': {
    categoryHue: 5,
    tone: 'category',
  },
  'ReconciliationResult.pending': { icon: 'lucide:clock-3', tone: 'queued' },
  'ReconciliationResult.filled': {
    icon: 'lucide:circle-check',
    tone: 'success',
  },
  'ReconciliationResult.not_filled': {
    icon: 'lucide:circle-check',
    tone: 'success',
  },
  'ReconciliationResult.partially_filled': {
    emphasis: 'solid',
    icon: 'lucide:triangle-alert',
    tone: 'warning',
  },
  'ReconciliationResult.cancelled': {
    icon: 'lucide:circle-minus',
    tone: 'neutral',
  },
  'ReconciliationResult.unresolvable': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'RedeemPolicy.manual': { categoryHue: 2, tone: 'category' },
  'RedeemPolicy.auto': { categoryHue: 1, tone: 'category' },
  'ReportFactDeliveryStatus.pending': {
    icon: 'lucide:clock-3',
    tone: 'queued',
  },
  'ReportFactDeliveryStatus.delivering': {
    icon: 'lucide:circle-check',
    tone: 'success',
  },
  'ReportFactDeliveryStatus.retrying': { categoryHue: 2, tone: 'category' },
  'ReportFactDeliveryStatus.failed': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'ReportFactDeliveryStatus.verified': { categoryHue: 8, tone: 'category' },
  'ReportFactDeliveryStatus.cancelled': {
    icon: 'lucide:circle-minus',
    tone: 'neutral',
  },
  'ReportKind.top_n': { categoryHue: 6, tone: 'category' },
  'ReportKind.shadow_top_n': { categoryHue: 5, tone: 'category' },
  'ReportKind.post_run_audit': { categoryHue: 6, tone: 'category' },
  'ReportRunStatus.queued': { icon: 'lucide:clock-3', tone: 'queued' },
  'ReportRunStatus.running': {
    emphasis: 'solid',
    icon: 'lucide:loader-circle',
    tone: 'running',
  },
  'ReportRunStatus.succeeded': { icon: 'lucide:circle-check', tone: 'success' },
  'ReportRunStatus.failed': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'ReportRunStatus.skipped': { icon: 'lucide:circle-minus', tone: 'neutral' },
  'ReportRunStatus.abandoned': { categoryHue: 1, tone: 'category' },
  'ReportRunTerminalReason.coalesced_by_newer_occurrence': {
    categoryHue: 10,
    tone: 'category',
  },
  'ReportRunTerminalReason.schedule_reconfigured': {
    categoryHue: 10,
    tone: 'category',
  },
  'ReportRunTerminalReason.queue_expired': {
    icon: 'lucide:circle-minus',
    tone: 'neutral',
  },
  'ReportRunTerminalReason.build_failed': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'ReportRunTerminalReason.lease_expired': {
    icon: 'lucide:circle-minus',
    tone: 'neutral',
  },
  'ReportScheduleGapReason.coordinator_lag': {
    categoryHue: 10,
    tone: 'category',
  },
  'ReportScheduleGapReason.coalesced_by_newer_occurrence': {
    categoryHue: 8,
    tone: 'category',
  },
  'ReportScheduleGapReason.schedule_reconfigured': {
    categoryHue: 12,
    tone: 'category',
  },
  'ReportTriggerKind.scheduled': { icon: 'lucide:clock-3', tone: 'queued' },
  'ReportTriggerKind.ad_hoc': { categoryHue: 4, tone: 'category' },
  'ResearchJobErrorCode.execution_failed': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'ResearchJobErrorCode.execution_retry_scheduled': {
    emphasis: 'solid',
    icon: 'lucide:triangle-alert',
    tone: 'warning',
  },
  'ResearchJobErrorCode.execution_retry_exhausted': {
    categoryHue: 4,
    tone: 'category',
  },
  'ResearchJobErrorCode.interrupted_by_restart': {
    categoryHue: 11,
    tone: 'category',
  },
  'ResearchJobErrorCode.interrupted_exceeded_attempts': {
    categoryHue: 2,
    tone: 'category',
  },
  'ResearchJobErrorCode.cancelled': {
    icon: 'lucide:circle-minus',
    tone: 'neutral',
  },
  'ResearchJobKind.dataset_build': { categoryHue: 5, tone: 'category' },
  'ResearchJobKind.model_train': { categoryHue: 8, tone: 'category' },
  'ResearchJobKind.backtest': { categoryHue: 11, tone: 'category' },
  'ResearchJobKind.bias_table_fit': { categoryHue: 4, tone: 'category' },
  'ResearchJobKind.model_calibration_fit': { categoryHue: 6, tone: 'category' },
  'ResearchJobKind.cpcv_backtest': { categoryHue: 8, tone: 'category' },
  'ResearchJobKind.feature_parity': { categoryHue: 12, tone: 'category' },
  'ResearchJobKind.feedback_truth_freeze': {
    categoryHue: 11,
    tone: 'category',
  },
  'ResearchJobKind.feedback_coverage': { categoryHue: 6, tone: 'category' },
  'ResearchJobKind.feedback_attribution': { categoryHue: 9, tone: 'category' },
  'ResearchJobKind.feedback_drift': { categoryHue: 3, tone: 'category' },
  'ResearchJobKind.feedback_recipe_plan': { categoryHue: 6, tone: 'category' },
  'ResearchJobKind.feedback_dataset_seal': { categoryHue: 8, tone: 'category' },
  'ResearchJobKind.feedback_training': {
    emphasis: 'solid',
    icon: 'lucide:loader-circle',
    tone: 'running',
  },
  'ResearchJobKind.feedback_calibration': { categoryHue: 2, tone: 'category' },
  'ResearchJobKind.feedback_cpcv': { categoryHue: 2, tone: 'category' },
  'ResearchJobKind.feedback_validation': { categoryHue: 1, tone: 'category' },
  'ResearchJobKind.feedback_comparison': { categoryHue: 11, tone: 'category' },
  'ResearchJobKind.feedback_shadow_bind': { categoryHue: 8, tone: 'category' },
  'ResearchJobKind.feedback_shadow': { categoryHue: 12, tone: 'category' },
  'ResearchJobKind.feedback_decision': { categoryHue: 6, tone: 'category' },
  'ResearchJobKind.trade_policy_fit': { categoryHue: 1, tone: 'category' },
  'ResearchJobKind.trade_policy_validation': {
    categoryHue: 7,
    tone: 'category',
  },
  'ResearchJobResultKind.training_dataset': {
    emphasis: 'solid',
    icon: 'lucide:loader-circle',
    tone: 'running',
  },
  'ResearchJobResultKind.model_version': { categoryHue: 5, tone: 'category' },
  'ResearchJobResultKind.backtest_report': { categoryHue: 1, tone: 'category' },
  'ResearchJobResultKind.backtest_path_set': {
    categoryHue: 7,
    tone: 'category',
  },
  'ResearchJobResultKind.calibration_artifact': {
    categoryHue: 6,
    tone: 'category',
  },
  'ResearchJobResultKind.feature_parity_run': {
    categoryHue: 11,
    tone: 'category',
  },
  'ResearchJobResultKind.feedback_truth_freeze_artifact': {
    categoryHue: 11,
    tone: 'category',
  },
  'ResearchJobResultKind.feedback_coverage_artifact': {
    categoryHue: 4,
    tone: 'category',
  },
  'ResearchJobResultKind.feedback_attribution_manifest': {
    categoryHue: 10,
    tone: 'category',
  },
  'ResearchJobResultKind.feedback_drift_artifact': {
    categoryHue: 9,
    tone: 'category',
  },
  'ResearchJobResultKind.candidate_recipe_plan_artifact': {
    icon: 'lucide:clock-3',
    tone: 'queued',
  },
  'ResearchJobResultKind.feedback_learning_stage_artifact': {
    categoryHue: 1,
    tone: 'category',
  },
  'ResearchJobResultKind.feedback_validation_artifact': {
    categoryHue: 9,
    tone: 'category',
  },
  'ResearchJobResultKind.feedback_comparison_artifact': {
    categoryHue: 7,
    tone: 'category',
  },
  'ResearchJobResultKind.shadow_binding_artifact': {
    categoryHue: 8,
    tone: 'category',
  },
  'ResearchJobResultKind.feedback_shadow_artifact': {
    categoryHue: 6,
    tone: 'category',
  },
  'ResearchJobResultKind.feedback_decision_artifact': {
    categoryHue: 8,
    tone: 'category',
  },
  'ResearchJobResultKind.trade_policy_artifact': {
    categoryHue: 11,
    tone: 'category',
  },
  'ResearchJobResultKind.trade_policy_validation_run': {
    categoryHue: 10,
    tone: 'category',
  },
  'ResearchJobStatus.queued': { icon: 'lucide:clock-3', tone: 'queued' },
  'ResearchJobStatus.awaiting_evidence': {
    icon: 'lucide:clock-3',
    tone: 'queued',
  },
  'ResearchJobStatus.retry_scheduled': {
    emphasis: 'solid',
    icon: 'lucide:triangle-alert',
    tone: 'warning',
  },
  'ResearchJobStatus.running': {
    emphasis: 'solid',
    icon: 'lucide:loader-circle',
    tone: 'running',
  },
  'ResearchJobStatus.succeeded': {
    icon: 'lucide:circle-check',
    tone: 'success',
  },
  'ResearchJobStatus.failed': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'ResearchJobStatus.cancelled': {
    icon: 'lucide:circle-minus',
    tone: 'neutral',
  },
  'ResearchReadinessEvidenceKind.retention_runway': {
    categoryHue: 5,
    tone: 'category',
  },
  'ResearchReadinessEvidenceKind.shadow_latency_profile': {
    categoryHue: 5,
    tone: 'category',
  },
  'ResolutionProjectionErrorCode.catalog_mapping_unavailable': {
    icon: 'lucide:circle-check',
    tone: 'success',
  },
  'ResolutionProjectionErrorCode.invalid_observation': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'ResolutionProjectionErrorCode.persistence_unavailable': {
    icon: 'lucide:circle-check',
    tone: 'success',
  },
  'ResolutionProjectionErrorCode.external_dependency_unavailable': {
    icon: 'lucide:circle-check',
    tone: 'success',
  },
  'ResolutionProjectionErrorCode.unexpected_transient': {
    categoryHue: 8,
    tone: 'category',
  },
  'ResolutionProjectionStatus.pending': {
    icon: 'lucide:clock-3',
    tone: 'queued',
  },
  'ResolutionProjectionStatus.delivering': {
    icon: 'lucide:circle-check',
    tone: 'success',
  },
  'ResolutionProjectionStatus.retry_scheduled': {
    emphasis: 'solid',
    icon: 'lucide:triangle-alert',
    tone: 'warning',
  },
  'ResolutionProjectionStatus.mapping_blocked': {
    emphasis: 'solid',
    icon: 'lucide:triangle-alert',
    tone: 'warning',
  },
  'ResolutionProjectionStatus.quarantined': {
    categoryHue: 11,
    tone: 'category',
  },
  'ResolutionProjectionStatus.excluded': { categoryHue: 1, tone: 'category' },
  'ResolutionProjectionStatus.verified': { categoryHue: 11, tone: 'category' },
  'ResolutionRemediationAction.requeue': { categoryHue: 9, tone: 'category' },
  'ResolutionRemediationAction.exclude': { categoryHue: 7, tone: 'category' },
  'ResolverTier.tier0_slug': { categoryHue: 10, tone: 'category' },
  'ResolverTier.tier1_template': { categoryHue: 2, tone: 'category' },
  'ResolverTier.override': { categoryHue: 8, tone: 'category' },
  'ResourceType.system': { categoryHue: 9, tone: 'category' },
  'ResourceType.market': { categoryHue: 10, tone: 'category' },
  'ResourceType.config': { categoryHue: 4, tone: 'category' },
  'ResourceType.publication': { categoryHue: 10, tone: 'category' },
  'ResourceType.materialization': { categoryHue: 5, tone: 'category' },
  'ResourceType.replay': { categoryHue: 7, tone: 'category' },
  'ResourceType.quant_report': { categoryHue: 12, tone: 'category' },
  'ResourceType.account_snapshot': { categoryHue: 6, tone: 'category' },
  'ResourceType.equity_snapshot': { categoryHue: 4, tone: 'category' },
  'ResourceType.order_intent': { categoryHue: 11, tone: 'category' },
  'ResourceType.execution_order': { categoryHue: 3, tone: 'category' },
  'ResourceType.position': { categoryHue: 7, tone: 'category' },
  'ResourceType.reconciliation': { categoryHue: 9, tone: 'category' },
  'ResourceType.settlement_redeem': { categoryHue: 8, tone: 'category' },
  'ResourceType.factor_definition': { categoryHue: 7, tone: 'category' },
  'ResourceType.operation_log': { categoryHue: 12, tone: 'category' },
  'ResourceType.user': { categoryHue: 3, tone: 'category' },
  'ResourceType.role': { categoryHue: 6, tone: 'category' },
  'ResourceType.menu': { categoryHue: 3, tone: 'category' },
  'ResourceType.permission': { categoryHue: 7, tone: 'category' },
  'RoleKind.builtin': { categoryHue: 3, tone: 'category' },
  'RoleKind.custom': { categoryHue: 5, tone: 'category' },
  'RoleStatus.enabled': { icon: 'lucide:circle-check', tone: 'success' },
  'RoleStatus.disabled': { icon: 'lucide:circle-minus', tone: 'neutral' },
  'RuntimeActivityActionKind.cancel_research_job': {
    categoryHue: 11,
    tone: 'category',
  },
  'RuntimeActivityActionKind.retry_research_job': {
    categoryHue: 7,
    tone: 'category',
  },
  'RuntimeActivityActionKind.retry_report_run': {
    categoryHue: 4,
    tone: 'category',
  },
  'RuntimeActivityActionKind.resolve_reconciliation': {
    categoryHue: 1,
    tone: 'category',
  },
  'RuntimeActivityDomain.research': { categoryHue: 2, tone: 'category' },
  'RuntimeActivityDomain.report': { categoryHue: 7, tone: 'category' },
  'RuntimeActivityDomain.execution': { categoryHue: 11, tone: 'category' },
  'RuntimeActivityDomain.reconciliation': { categoryHue: 2, tone: 'category' },
  'RuntimeActivityDomain.settlement': { categoryHue: 8, tone: 'category' },
  'RuntimeActivityStatus.pending': { icon: 'lucide:clock-3', tone: 'queued' },
  'RuntimeActivityStatus.running': {
    emphasis: 'solid',
    icon: 'lucide:loader-circle',
    tone: 'running',
  },
  'RuntimeActivityStatus.succeeded': {
    icon: 'lucide:circle-check',
    tone: 'success',
  },
  'RuntimeActivityStatus.failed': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'RuntimeActivityStatus.cancelled': {
    icon: 'lucide:circle-minus',
    tone: 'neutral',
  },
  'RuntimeActivityStatus.attention': { categoryHue: 5, tone: 'category' },
  'RuntimeActivityStatus.skipped': {
    icon: 'lucide:circle-minus',
    tone: 'neutral',
  },
  'SettlementAuthorizationState.not_required': {
    categoryHue: 6,
    tone: 'category',
  },
  'SettlementAuthorizationState.pending': {
    icon: 'lucide:clock-3',
    tone: 'queued',
  },
  'SettlementAuthorizationState.approved': {
    categoryHue: 10,
    tone: 'category',
  },
  'SettlementAuthorizationState.revoked': { categoryHue: 5, tone: 'category' },
  'SettlementAuthorizationState.consumed': { categoryHue: 5, tone: 'category' },
  'SettlementAuthorizationState.expired': {
    icon: 'lucide:circle-minus',
    tone: 'neutral',
  },
  'SettlementCaseState.discovered': { categoryHue: 6, tone: 'category' },
  'SettlementCaseState.prepared': { icon: 'lucide:clock-3', tone: 'queued' },
  'SettlementCaseState.submitted': {
    emphasis: 'solid',
    icon: 'lucide:loader-circle',
    tone: 'running',
  },
  'SettlementCaseState.confirmed': {
    icon: 'lucide:circle-check',
    tone: 'success',
  },
  'SettlementCaseState.retry_scheduled': {
    emphasis: 'solid',
    icon: 'lucide:triangle-alert',
    tone: 'warning',
  },
  'SettlementCaseState.reconciliation_required': {
    categoryHue: 3,
    tone: 'category',
  },
  'SettlementCaseState.manual_required': {
    emphasis: 'solid',
    icon: 'lucide:triangle-alert',
    tone: 'warning',
  },
  'SettlementCaseState.not_required': { categoryHue: 1, tone: 'category' },
  'SettlementEffectivePolicy.automatic_eligible': {
    categoryHue: 1,
    tone: 'category',
  },
  'SettlementEffectivePolicy.manual_only': {
    categoryHue: 11,
    tone: 'category',
  },
  'SettlementFailureCode.route_not_ready': {
    icon: 'lucide:circle-check',
    tone: 'success',
  },
  'SettlementFailureCode.balance_mismatch': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'SettlementFailureCode.simulation_reverted': {
    categoryHue: 5,
    tone: 'category',
  },
  'SettlementFailureCode.transport_uncertain': {
    categoryHue: 11,
    tone: 'category',
  },
  'SettlementFailureCode.submission_rejected': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'SettlementFailureCode.relayer_terminal_failure': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'SettlementFailureCode.on_chain_reverted': {
    categoryHue: 1,
    tone: 'category',
  },
  'SettlementFailureCode.receipt_evidence_mismatch': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'SettlementFailureCode.payout_mismatch': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'SettlementFailureCode.deployment_changed': {
    categoryHue: 6,
    tone: 'category',
  },
  'SettlementFailureCode.authorization_invalid': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'SettlementFailureCode.execution_not_quiescent': {
    categoryHue: 4,
    tone: 'category',
  },
  'SettlementFailureCode.lease_lost': { categoryHue: 1, tone: 'category' },
  'SettlementFailureCode.ledger_unavailable': {
    icon: 'lucide:circle-check',
    tone: 'success',
  },
  'SettlementFailureCode.local_invariant': {
    categoryHue: 12,
    tone: 'category',
  },
  'SettlementFailureCode.external_evidence_incomplete': {
    categoryHue: 8,
    tone: 'category',
  },
  'SettlementGovernedActionKind.outcome_token_approval': {
    categoryHue: 3,
    tone: 'category',
  },
  'SettlementGovernedActionKind.outcome_token_revocation': {
    categoryHue: 6,
    tone: 'category',
  },
  'SettlementGovernedActionKind.canary_grant': {
    categoryHue: 8,
    tone: 'category',
  },
  'SettlementGovernedActionState.authorized': {
    categoryHue: 7,
    tone: 'category',
  },
  'SettlementGovernedActionState.retry_scheduled': {
    emphasis: 'solid',
    icon: 'lucide:triangle-alert',
    tone: 'warning',
  },
  'SettlementGovernedActionState.consumed': {
    categoryHue: 6,
    tone: 'category',
  },
  'SettlementGovernedActionState.revoked': { categoryHue: 4, tone: 'category' },
  'SettlementGovernedActionState.expired': {
    icon: 'lucide:circle-minus',
    tone: 'neutral',
  },
  'SettlementGovernedActionState.reconciliation_required': {
    categoryHue: 3,
    tone: 'category',
  },
  'SettlementGovernedActionState.failed': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'SettlementReadinessStatus.unchecked': { categoryHue: 3, tone: 'category' },
  'SettlementReadinessStatus.ready': {
    icon: 'lucide:circle-check',
    tone: 'success',
  },
  'SettlementReadinessStatus.blocked': {
    emphasis: 'solid',
    icon: 'lucide:triangle-alert',
    tone: 'warning',
  },
  'SettlementReconciliationState.not_required': {
    categoryHue: 2,
    tone: 'category',
  },
  'SettlementReconciliationState.awaiting_relayer_hash': {
    icon: 'lucide:clock-3',
    tone: 'queued',
  },
  'SettlementReconciliationState.awaiting_receipt': {
    icon: 'lucide:clock-3',
    tone: 'queued',
  },
  'SettlementReconciliationState.evidence_mismatch': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'SettlementReconciliationState.operator_review_required': {
    icon: 'lucide:clock-3',
    tone: 'queued',
  },
  'SettlementReconciliationState.reconciled': {
    icon: 'lucide:circle-check',
    tone: 'success',
  },
  'SettlementRoute.standard_v2': { categoryHue: 12, tone: 'category' },
  'SettlementRoute.neg_risk_v2': { categoryHue: 5, tone: 'category' },
  'SettlementSubmissionKind.direct_eoa': { categoryHue: 8, tone: 'category' },
  'SettlementSubmissionKind.relayer': { categoryHue: 1, tone: 'category' },
  'SettlementSubmissionKind.externally_observed': {
    categoryHue: 4,
    tone: 'category',
  },
  'SettlementSubmissionPurpose.outcome_token_approval': {
    categoryHue: 11,
    tone: 'category',
  },
  'SettlementSubmissionPurpose.outcome_token_revocation': {
    categoryHue: 6,
    tone: 'category',
  },
  'SettlementSubmissionPurpose.redeem': { categoryHue: 7, tone: 'category' },
  'SettlementSubmissionState.prepared': {
    icon: 'lucide:clock-3',
    tone: 'queued',
  },
  'SettlementSubmissionState.dispatching': {
    categoryHue: 12,
    tone: 'category',
  },
  'SettlementSubmissionState.awaiting_chain_hash': {
    icon: 'lucide:clock-3',
    tone: 'queued',
  },
  'SettlementSubmissionState.awaiting_finality': {
    icon: 'lucide:clock-3',
    tone: 'queued',
  },
  'SettlementSubmissionState.confirmed': {
    icon: 'lucide:circle-check',
    tone: 'success',
  },
  'SettlementSubmissionState.failed': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'SettlementWritePolicy.disabled': {
    icon: 'lucide:circle-minus',
    tone: 'neutral',
  },
  'SettlementWritePolicy.governed_canary': {
    categoryHue: 11,
    tone: 'category',
  },
  'SettlementWritePolicy.semi_auto': { categoryHue: 10, tone: 'category' },
  'SettlementWritePolicy.auto': { categoryHue: 9, tone: 'category' },
  'ShadowBindingStatus.active': {
    icon: 'lucide:circle-check',
    tone: 'success',
  },
  'ShadowBindingStatus.rejected': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'ShadowBindingStatus.promoted': { categoryHue: 11, tone: 'category' },
  'ShadowBindingStatus.cancelled': {
    icon: 'lucide:circle-minus',
    tone: 'neutral',
  },
  'Side.BUY': { categoryHue: 9, tone: 'category' },
  'Side.SELL': { categoryHue: 1, tone: 'category' },
  'SourceSliceStatus.materializing': {
    emphasis: 'solid',
    icon: 'lucide:loader-circle',
    tone: 'running',
  },
  'SourceSliceStatus.ready': { icon: 'lucide:circle-check', tone: 'success' },
  'SourceSliceStatus.failed': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'StalenessLevel.fresh': { categoryHue: 12, tone: 'category' },
  'StalenessLevel.acceptable': { categoryHue: 2, tone: 'category' },
  'StalenessLevel.stale': {
    emphasis: 'solid',
    icon: 'lucide:triangle-alert',
    tone: 'warning',
  },
  'StalenessLevel.expired': { icon: 'lucide:circle-minus', tone: 'neutral' },
  'TickSize.0.1': { categoryHue: 11, tone: 'category' },
  'TickSize.0.01': { categoryHue: 9, tone: 'category' },
  'TickSize.0.005': { categoryHue: 7, tone: 'category' },
  'TickSize.0.0025': { categoryHue: 7, tone: 'category' },
  'TickSize.0.001': { categoryHue: 3, tone: 'category' },
  'TickSize.0.0001': { categoryHue: 9, tone: 'category' },
  'TradePolicyGovernanceAction.validate': { categoryHue: 4, tone: 'category' },
  'TradePolicyGovernanceAction.publish': { categoryHue: 5, tone: 'category' },
  'TradePolicyGovernanceAction.retire': { categoryHue: 3, tone: 'category' },
  'TradePolicyStatus.draft': { icon: 'lucide:clock-3', tone: 'queued' },
  'TradePolicyStatus.validated': { categoryHue: 10, tone: 'category' },
  'TradePolicyStatus.published': {
    icon: 'lucide:circle-check',
    tone: 'success',
  },
  'TradePolicyStatus.retired': { icon: 'lucide:circle-minus', tone: 'neutral' },
  'TradePolicyTrialScope.candidate': { icon: 'lucide:clock-3', tone: 'queued' },
  'TradePolicyTrialScope.fold': { categoryHue: 5, tone: 'category' },
  'TradePolicyTrialScope.path': { categoryHue: 1, tone: 'category' },
  'TradePolicyTrialScope.latency_stress': { categoryHue: 1, tone: 'category' },
  'TradePolicyTrialStatus.succeeded': {
    icon: 'lucide:circle-check',
    tone: 'success',
  },
  'TradePolicyTrialStatus.failed': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'TradePolicyTrialStatus.cancelled': {
    icon: 'lucide:circle-minus',
    tone: 'neutral',
  },
  'TradePolicyValidationStatus.running': {
    emphasis: 'solid',
    icon: 'lucide:loader-circle',
    tone: 'running',
  },
  'TradePolicyValidationStatus.succeeded': {
    icon: 'lucide:circle-check',
    tone: 'success',
  },
  'TradePolicyValidationStatus.failed': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'TradePolicyValidationStatus.cancelled': {
    icon: 'lucide:circle-minus',
    tone: 'neutral',
  },
  'TrainingDatasetStatus.planned': { icon: 'lucide:clock-3', tone: 'queued' },
  'TrainingDatasetStatus.building': {
    emphasis: 'solid',
    icon: 'lucide:loader-circle',
    tone: 'running',
  },
  'TrainingDatasetStatus.insufficient_labels': {
    emphasis: 'solid',
    icon: 'lucide:triangle-alert',
    tone: 'warning',
  },
  'TrainingDatasetStatus.ready': {
    icon: 'lucide:circle-check',
    tone: 'success',
  },
  'TrainingDatasetStatus.expired': {
    icon: 'lucide:circle-minus',
    tone: 'neutral',
  },
  'TrainingDatasetStatus.failed': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'UserStatus.active': { icon: 'lucide:circle-check', tone: 'success' },
  'UserStatus.disabled': { icon: 'lucide:circle-minus', tone: 'neutral' },
  'VenueOrderStatus.filled': { icon: 'lucide:circle-check', tone: 'success' },
  'VenueOrderStatus.partially_filled': {
    emphasis: 'solid',
    icon: 'lucide:triangle-alert',
    tone: 'warning',
  },
  'VenueOrderStatus.rejected': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
  'VenueOrderStatus.cancelled': {
    icon: 'lucide:circle-minus',
    tone: 'neutral',
  },
  'VenueOrderStatus.open': { categoryHue: 1, tone: 'category' },
  'VenueOrderStatus.expired': { icon: 'lucide:circle-minus', tone: 'neutral' },
  'VenueTradeStatus.matched': { icon: 'lucide:circle-check', tone: 'success' },
  'VenueTradeStatus.mined': { categoryHue: 4, tone: 'category' },
  'VenueTradeStatus.confirmed': {
    icon: 'lucide:circle-check',
    tone: 'success',
  },
  'VenueTradeStatus.retrying': { categoryHue: 1, tone: 'category' },
  'VenueTradeStatus.failed': {
    emphasis: 'solid',
    icon: 'lucide:circle-x',
    tone: 'danger',
  },
} as const satisfies Record<EnumMemberKey, EnumPresentation>;

export const SEMANTIC_ENUM_PRESENTATION = semanticPresentations();

export const CATEGORY_ENUM_PRESENTATION = Object.fromEntries(
  Object.entries(GENERATED_ENUM_PRESENTATION).filter(
    ([key]) => !(key in SEMANTIC_ENUM_PRESENTATION),
  ),
) as Partial<Record<EnumMemberKey, EnumPresentation>>;

export const ENUM_PRESENTATION = {
  ...GENERATED_ENUM_PRESENTATION,
  ...SEMANTIC_ENUM_PRESENTATION,
} as const satisfies Record<EnumMemberKey, EnumPresentation>;

export function enumMemberKey<Name extends EnumName>(
  name: Name,
  value: EnumValue<Name>,
): EnumMemberKey {
  return `${name}.${value}` as EnumMemberKey;
}

export function enumPresentation<Name extends EnumName>(
  name: Name,
  value: EnumValue<Name>,
): EnumPresentation {
  return ENUM_PRESENTATION[enumMemberKey(name, value)];
}
